baseURL = "http://evovetech.github.io"
languageCode = "en-us"
title = "evove.tech"
theme = "steam"
# Enable Google Analytics be inserting your tracking code
googleAnalytics = ""
# Number of posts per page
paginate = 10

[params]
	title = "<span class='evove'>evove</span><span class='dot'>.</span><span class='tech'>tech</span>"
	subtitle = "your tech <span class='evove'>evo</span><sub>ve</sub><span class='tech'>lution</span> begins here"
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themecolor = "blue"

	# Link custom assets relative to /static
	favicon   = "favicon.png"
	customCSS = []
	customJS  = []

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "evove.tech"
	bio = "programmer - blogger - coffee aficionado"
	description = "Your description of the blog"

	# Link your social networks (optional)
	location = "Austin, TX"
	twitter = ""
	linkedin = ""
	googleplus = ""
	facebook = ""
	instagram = ""
	github = "evovetech"
	gitlab = ""
	bitbucket = ""

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
